Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -79,14 +79,14 @@ jobs:
         run: |
           ls -R deployment-manifests/manifests
           cat deployment-manifests/manifests/frontend-deployment.yml || echo "frontend-deployment.yml not found"
-          cat deployment-manifests/manifests/frontend-svc.yml || echo "frontend-svc.yml not found"
           cat deployment-manifests/manifests/backend.yml || echo "backend.yml not found"
           cat deployment-manifests/manifests/mongo-deployment.yml || echo "mongo-deployment.yml not found"
 
-      - name: Update image tags
+      - name: Apply manifests
         run: |
-          sed -i -E "s|iamvegetaaj/frontend:pr-[0-9]+-[a-f0-9]+|iamvegetaaj/frontend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}|g" deployment-manifests/manifests/frontend-deployment.yml
-          sed -i -E "s|iamvegetaaj/node-backend:pr-[0-9]+-[a-f0-9]+|iamvegetaaj/node-backend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}|g" deployment-manifests/manifests/backend-deployment.yml
+          kubectl apply -f deployment-manifests/manifests/frontend-deployment.yml || { echo "Failed to apply frontend-deployment.yml"; exit 1; }
+          kubectl apply -f deployment-manifests/manifests/backend-deployment.yml || { echo "Failed to apply backend-deployment.yml"; exit 1; }
+          kubectl apply -f deployment-manifests/manifests/mongo-deployment.yml || { echo "Failed to apply mongo-deployment.yml"; exit 1; }
 
 
       - name: Commit and push updated image tags
